server:
  port: 8080
  servlet:
    application-display-name:

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 123456789

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      show_sql: false
      format_sql: true

logging.level:
  org.springframework.boot.autoconfigure: ERROR

app:
  secret: asdfghjkl
  refreshSecret: asdfghjkl
  JWT_ACCESS_EXPIRE: 3600000
  JWT_REFRESH_EXPIRE: 604,800,000